name: Swift

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bundle exec fastlane buildLane
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/GitHubActions.app
    - name: Upload runner
      uses: actions/upload-artifact@v1
      with:
        name: runner
        path: derivedData/Build/Products/Debug-iphonesimulator/GitHubActionsUITests-Runner.app
  
  unitTests:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/GitHubActions.app
    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
  
  uiTests:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/GitHubActions.app
    - name: Download runner
      uses: actions/download-artifact@v1
      with:
        name: runner
        path: derivedData/Build/Products/Debug-iphonesimulator/GitHubActionsUITests-Runner.app
    - name: Run ui tests
      run: bundle exec fastlane uiTestLane
